import "./globals.css";
import type { Metadata } from "next";
import { yekan } from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className={yekan.className}>
      <body>{children}</body>
    </html>
  );
}
